# Generated by Django 4.0.1 on 2022-01-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantasModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='img')),
                ('link', models.CharField(max_length=5000)),
            ],
            options={
                'verbose_name': 'Planta',
                'verbose_name_plural': 'Platas',
                'ordering': ['id'],
            },
        ),
    ]
